### ISSUE TITLE
Investigate possible issue with process generation

### ISSUE THREAD

**Issue by delas** [delas/plg#7]
Received this possible bug via email:
> when using the API I encountered a rare exception that sometimes triggers when generating large amounts of models. It's a NullPointerException in file ProcessGenerator.java (line 229). By the looks of the file it had to do with Data Object generation, I disabled it and the exception went away. I don't know if it has to do with what you just told us (the BPMN exporter not handling data objects very well) or it's something else. I thought you might be interested in knowing.

**Comment by chrsdrdt** [comment]
I can confirm and reproduce this bug:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at plg.generator.process.ProcessGenerator.newXorBranches(ProcessGenerator.java:229)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:111)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:179)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newXorBranches(ProcessGenerator.java:227)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:111)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:178)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:178)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:179)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:178)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newSequence(ProcessGenerator.java:178)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:105)
        at plg.generator.process.ProcessGenerator.newXorBranches(ProcessGenerator.java:227)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:111)
        at plg.generator.process.ProcessGenerator.newLoopBranch(ProcessGenerator.java:255)
        at plg.generator.process.ProcessGenerator.newInternalPattern(ProcessGenerator.java:114)
        at plg.generator.process.ProcessGenerator.begin(ProcessGenerator.java:83)
        at plg.generator.process.ProcessGenerator.randomizeProcess(ProcessGenerator.java:59)
        at plg.gui.controller.ProcessesController.randomProcess(ProcessesController.java:75)
        at plg.gui.widgets.MainToolbar$1.actionPerformed(MainToolbar.java:77)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

Here are the settings I used
![Settings](https://user-images.githubusercontent.com/64904883/106012900-325ce900-60bc-11eb-8a37-03b16ec427c0.png)

**Comment by delas** [comment]
Should be closed in https://github.com/delas/plg/releases/tag/2.1.0
